jaffle_shop:
  target: postgres
  outputs:
    postgres:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      user: postgres
      pass: postgres
      port: 5432
      schema: dbt_unit_testing_jaffle_shop
      dbname: postgres
      threads: 1